# Importing numpy library

In [3]:
import numpy as np

# creating 1D Array

In [66]:
a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([6,7,8,9,10])
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


# Basic operations on array

In [69]:
#Addition of two arrays
print("Addition of two arrays is ")
print(a1+a2)
#Subtraction of two arrays
print("Subtraction of two arrays is")
print(a2-a1)

Addition of two arrays is 
[ 7  9 11 13 15]
Subtraction of two arrays is
[5 5 5 5 5]


# Creating numpy 2D array of random integers between 1 and 30

In [7]:
arr=np.random.randint(1,30,size=(6,6))
print(arr)

[[29  3 14 26 20  7]
 [ 4  3 12 18 19  2]
 [22 28 25 18  7 17]
 [ 2 22 22 19 18 13]
 [26  2 11 16  9 16]
 [16  7 14  5  9 14]]


# Transposing of the matrix

In [20]:
arr_t=arr.T
print(arr_t)

[[20 26 29 24  4  9]
 [ 6 13 23 22 18 21]
 [25 21  2  6 11  2]
 [11 11 13 24  7 22]
 [ 8 25 12  1 19  3]
 [14 15  5 11 10  4]]


# Vectorized computations of 2d array

In [25]:
print("Addition of matrix with its transpose ")
print(arr+arr_t)
print("Subtraction of matrix with its transpose ")
print(arr-arr_t)

Addition of matrix with its transpose 
[[40 32 54 35 12 23]
 [32 26 44 33 43 36]
 [54 44  4 19 23  7]
 [35 33 19 48  8 33]
 [12 43 23  8 38 13]
 [23 36  7 33 13  8]]
Subtraction of matrix with its transpose 
[[  0 -20  -4 -13   4   5]
 [ 20   0  -2 -11   7  -6]
 [  4   2   0   7   1   3]
 [ 13  11  -7   0  -6 -11]
 [ -4  -7  -1   6   0   7]
 [ -5   6  -3  11  -7   0]]


# Array properties

In [28]:
print("\nArray Shape:\n", arr.shape)
print("Array Size:\n", arr.size)
print("Array Dimension:\n", arr.ndim)
print("Array Data Type:\n", arr.dtype)


Array Shape:
 (6, 6)
Array Size:
 36
Array Dimension:
 2
Array Data Type:
 int32


# changing elements in 1st row

In [33]:
arr[0]=[4,5,6,7,8,9]
print(arr)

[[ 4  5  6  7  8  9]
 [26 13 21 11 25 15]
 [29 23  2 13 12  5]
 [24 22  6 24  1 11]
 [ 4 18 11  7 19 10]
 [ 9 21  2 22  3  4]]


# Array indexing

In [36]:
print("Element of 1st row and 3rd column is",arr[0][2])
print("Element of 5th row and 4th column is",arr[4][3])

Element of 1st row and 3rd column is 6
Element of 5th row and 4th column is 7


# Array Slicing

slicing array to a sub array

In [45]:
sub_arr=arr[:3,:3]   #sub array of 1st 3 rows and 1st 3 columns of arr
print(sub_arr)

[[ 4  5  6]
 [26 13 21]
 [29 23  2]]


# Reshaping of array

reshaping 6*6 matrix to 9*4 matrix

In [51]:
reshaped_arr=arr.reshape(9,4)
print("Reshaped array is")
print(reshaped_arr)

Reshaped array is
[[ 4  5  6  7]
 [ 8  9 26 13]
 [21 11 25 15]
 [29 23  2 13]
 [12  5 24 22]
 [ 6 24  1 11]
 [ 4 18 11  7]
 [19 10  9 21]
 [ 2 22  3  4]]


# Mathematical Operations

adding 2 to every element of the arr

In [57]:
arr_2=arr+2
print("array matrix after adding 2 to each elemant of the arr")
print(arr_2)

array matrix after adding 2 to each elemant of the arr
[[ 6  7  8  9 10 11]
 [28 15 23 13 27 17]
 [31 25  4 15 14  7]
 [26 24  8 26  3 13]
 [ 6 20 13  9 21 12]
 [11 23  4 24  5  6]]


# sum of elements of an array

In [13]:
#sum of elements of each row and column
print("sum of all elements")
print(np.sum(arr) )#sum of all elements
print("sum of all elements of each column wise")
print(np.sum(arr,axis=0))  # Column wise
print("sum of all elements of each column wise")
print(np.sum(arr,axis=1))  # Row wise

sum of all elements
515
sum of all elements of each column wise
[ 99  65  98 102  82  69]
sum of all elements of each column wise
[ 99  58 117  96  80  65]


# mean, median, standard deviation

In [27]:
print("mean of all elements ")  
print(np.mean(arr))
print("Median of all elements")
print(np.median(arr))
print("standard deviation of all elements")
print(np.std(arr))
print("mean of all elements of each column wise")
print(np.mean(arr,axis=0))  # Column wise
print("mean of all elements of each column wise")
print(np.mean(arr,axis=1))  # Row wise
print("median of all elements of each column wise")
print(np.median(arr,axis=0))  # Column wise
print("median of all elements of each column wise")
print(np.median(arr,axis=1))  # Row wise

mean of all elements 
14.305555555555555
Median of all elements
15.0
standard deviation of all elements
7.887470529772183
mean of all elements of each column wise
[16.5        10.83333333 16.33333333 17.         13.66666667 11.5       ]
mean of all elements of each column wise
[16.5         9.66666667 19.5        16.         13.33333333 10.83333333]
median of all elements of each column wise
[19.   5.  14.  18.  13.5 13.5]
median of all elements of each column wise
[17.   8.  20.  18.5 13.5 11.5]


# Data Analysis Using Numpy

# Correlation Coefficient of two arrays

In [36]:
arr1=np.random.randint(1,100,10)
arr2=np.random.randint(1,100,10)
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Correalation Matrix is ")
print(np.corrcoef(arr1,arr2))

Array 1:
[31 48 24 13 23  8 33 73 53 16]
Array 2:
[35 56 61 71 41 83 39 22 75 39]
Correalation Matrix is 
[[ 1.         -0.42378593]
 [-0.42378593  1.        ]]


# Percentile 

In [53]:
print("80th percentile of array 1 is ")
print(np.percentile(arr1,80))

80th percentile of array 1 is 
49.0


# Advantages of Numpy

Performance and Speed: NumPy is much faster than traditional Python data structures like lists due to its C implementation, vectorized operations, and use of optimized libraries

Memory Efficiency: NumPy arrays use less memory as they store elements of the same type in contiguous blocks, unlike Python lists that require memory for both data and type information.

Powerful Array Operations: Supports broadcasting, universal functions (ufuncs), and rich mathematical functions for efficient element-wise operations and complex computations.

Support for Multi-Dimensional Arrays: Allows for easy creation, reshaping, slicing, and manipulation of multi-dimensional arrays, essential for handling large datasets and tensors.

# Real world applications

Machine Learning: Efficient data preprocessing, feature scaling, and implementation of algorithms like regression and neural networks.

Finance: Time series analysis, portfolio optimization, and Monte Carlo simulations for risk assessment.

Scientific Research: Simulations and data analysis in physics, biology, and astronomy.

Image Processing: Image manipulation, filtering, and medical imaging tasks.

AI and Deep Learning: Neural network computations and natural language processing.